In [19]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import plotly.express as px
# import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from imblearn.over_sampling import SMOTE
from pycaret.classification import *
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
import xgboost as cgb
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import confusion_matrix,roc_curve,auc,classification_report
import pickle

In [33]:
df = pd.read_csv('transaction_dataset.csv',index_col=0)

In [21]:
pd.set_option('display.max_rows',None)

In [34]:
df.head()

,Index,Address,FLAG,Avg min between sent tnx,Avg min between received tnx,Time Diff between first and last (Mins),Sent tnx,Received Tnx,Number of Created Contracts,Unique Received From Addresses,...,ERC20 min val sent,ERC20 max val sent,ERC20 avg val sent,ERC20 min val sent contract,ERC20 max val sent contract,ERC20 avg val sent contract,ERC20 uniq sent token name,ERC20 uniq rec token name,ERC20 most sent token type,ERC20_most_rec_token_type
0,1,0x00009277775ac7d0d59eaad8fee3d10ac6c805e8,0,844.26,1093.71,704785.63,721,89,0,40,...,0.000000,1.683100e+07,271779.920000,0.0,0.0,0.0,39.0,57.0,Cofoundit,Numeraire
1,2,0x0002b44ddb1476db43c868bd494422ee4c136fed,0,12709.07,2958.44,1218216.73,94,8,0,5,...,2.260809,2.260809e+00,2.260809,0.0,0.0,0.0,1.0,7.0,Livepeer Token,Livepeer Token
2,3,0x0002bda54cb772d040f779e88eb453cac0daa244,0,246194.54,2434.02,516729.30,2,10,0,10,...,0.000000,0.000000e+00,0.000000,0.0,0.0,0.0,0.0,8.0,NaN,XENON
3,4,0x00038e6ba2fd5c09aedb96697c8d7b8fa6632e5e,0,10219.60,15785.09,397555.90,25,9,0,7,...,100.000000,9.029231e+03,3804.076893,0.0,0.0,0.0,1.0,11.0,Raiden,XENON
4,5,0x00062d1dd1afb6fb02540ddad9cdebfe568e0d89,0,36.61,10707.77,382472.42,4598,20,1,7,...,0.000000,4.500000e+04,13726.659220,0.0,0.0,0.0,6.0,27.0,StatusNetwork,EOS

In [23]:
df.shape

(9841, 51)

In [24]:
setup(df,target="FLAG",session_id = 85)

In [25]:
compare_models()

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='sqrt',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_samples_leaf=1,
                       min_samples_split=2, min_weight_fraction_leaf=0.0,
                       monotonic_cst=None, n_estimators=100, n_jobs=-1,
                       oob_score=False, random_state=85, verbose=0,
                       warm_start=False)

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9841 entries, 0 to 9840
Data columns (total 50 columns):
 #   Column                                                Non-Null Count  Dtype
---  ------                                                --------------  -----
 0   Index                                                 9841 non-null   int64
 1   Address                                               9841 non-null   object
 2   FLAG                                                  9841 non-null   int64
 3   Avg min between sent tnx                              9841 non-null   float64
 4   Avg min between received tnx                          9841 non-null   float64
 5   Time Diff between first and last (Mins)               9841 non-null   float64
 6   Sent tnx                                              9841 non-null   int64
 7   Received Tnx                                          9841 non-null   int64
 8   Number of Created Contracts                           9841 non-null   int64
 9   Unique Received From Addresses                        9841 non-null   int64
 10  Unique Sent To Addresses                              9841 non-null   int64
 11  min value received                                    9841 non-null   float64
 12  max value received                                    9841 non-null   float64
 13  avg val received                                      9841 non-null   float64
 14  min val sent                                          9841 non-null   float64
 15  max val sent                                          9841 non-null   float64
 16  avg val sent                                          9841 non-null   float64
 17  min value sent to contract                            9841 non-null   float64
 18  max val sent to contract                              9841 non-null   float64
 19  avg value sent to contract                            9841 non-null   float64
 20  total transactions (including tnx to create contract  9841 non-null   int64
 21  total Ether sent                                      9841 non-null   float64
 22  total ether received                                  9841 non-null   float64
 23  total ether sent contracts                            9841 non-null   float64
 24  total ether balance                                   9841 non-null   float64
 25   Total ERC20 tnxs                                     9012 non-null   float64
 26   ERC20 total Ether received                           9012 non-null   float64
 27   ERC20 total ether sent                               9012 non-null   float64
 28   ERC20 total Ether sent contract                      9012 non-null   float64
 29   ERC20 uniq sent addr                                 9012 non-null   float64
 30   ERC20 uniq rec addr                                  9012 non-null   float64
 31   ERC20 uniq sent addr.1                               9012 non-null   float64
 32   ERC20 uniq rec contract addr                         9012 non-null   float64
 33   ERC20 avg time between sent tnx                      9012 non-null   float64
 34   ERC20 avg time between rec tnx                       9012 non-null   float64
 35   ERC20 avg time between rec 2 tnx                     9012 non-null   float64
 36   ERC20 avg time between contract tnx                  9012 non-null   float64
 37   ERC20 min val rec                                    9012 non-null   float64
 38   ERC20 max val rec                                    9012 non-null   float64
 39   ERC20 avg val rec                                    9012 non-null   float64
 40   ERC20 min val sent                                   9012 non-null   float64
 41   ERC20 max val sent                                   9012 non-null   float64
 42   ERC20 avg val sent                                   9012 non-null   float64
 43   ERC20 min val sent contract                          9012 non-null   float64
 44   ERC20 max val sent contract                          9012 non-null   float64
 45   ERC20 avg val sent contract                          9012 non-null   float64
 46   ERC20 uniq sent token name                           9012 non-null   float64
 47   ERC20 uniq rec token name                            9012 non-null   float64
 48   ERC20 most sent token type                           7144 non-null   object
 49   ERC20_most_rec_token_type                            8970 non-null   object
dtypes: float64(39), int64(8), object(3)
memory usage: 3.8+ MB

In [36]:
for col in df :
    print(f'{col}',len(df[col].unique()))

Index 4729
Address 9816
FLAG 2
Avg min between sent tnx 5013
Avg min between received tnx 6223
Time Diff between first and last (Mins) 7810
Sent tnx 641
Received Tnx 727
Number of Created Contracts 20
Unique Received From Addresses 256
Unique Sent To Addresses 258
min value received 4589
max value received  6302
avg val received 6767
min val sent 4719
max val sent 6647
avg val sent 5854
min value sent to contract 3
max val sent to contract 4
avg value sent to contract 4
total transactions (including tnx to create contract 897
total Ether sent 5868
total ether received 6728
total ether sent contracts 4
total ether balance 5717
 Total ERC20 tnxs 301
 ERC20 total Ether received 3461
 ERC20 total ether sent 1416
 ERC20 total Ether sent contract 30
 ERC20 uniq sent addr 108
 ERC20 uniq rec addr 148
 ERC20 uniq sent addr.1 5
 ERC20 uniq rec contract addr 124
 ERC20 avg time between sent tnx 2
 ERC20 avg time between rec tnx 2
 ERC20 avg time between rec 2 tnx 2
 ERC20 avg time between contract tnx 2
 ERC20 min val rec 1277
 ERC20 max val rec 2648
 ERC20 avg val rec 3381
 ERC20 min val sent 477
 ERC20 max val sent 1131
 ERC20 avg val sent 1310
 ERC20 min val sent contract 2
 ERC20 max val sent contract 2
 ERC20 avg val sent contract 2
 ERC20 uniq sent token name 71
 ERC20 uniq rec token name 122
 ERC20 most sent token type 305
 ERC20_most_rec_token_type 467

In [37]:
df.select_dtypes(include=['float','int']).describe()

,Index,FLAG,Avg min between sent tnx,Avg min between received tnx,Time Diff between first and last (Mins),Sent tnx,Received Tnx,Number of Created Contracts,Unique Received From Addresses,Unique Sent To Addresses,...,ERC20 max val rec,ERC20 avg val rec,ERC20 min val sent,ERC20 max val sent,ERC20 avg val sent,ERC20 min val sent contract,ERC20 max val sent contract,ERC20 avg val sent contract,ERC20 uniq sent token name,ERC20 uniq rec token name
count,9841.000000,9841.000000,9841.000000,9841.000000,9.841000e+03,9841.000000,9841.000000,9841.000000,9841.000000,9841.000000,...,9.012000e+03,9.012000e+03,9.012000e+03,9.012000e+03,9.012000e+03,9012.0,9012.0,9012.0,9012.000000,9012.000000
mean,1815.049893,0.221421,5086.878721,8004.851184,2.183333e+05,115.931714,163.700945,3.729702,30.360939,25.840159,...,1.252524e+08,4.346203e+06,1.174126e+04,1.303594e+07,6.318389e+06,0.0,0.0,0.0,1.384931,4.826676
std,1222.621830,0.415224,21486.549974,23081.714801,3.229379e+05,757.226361,940.836550,141.445583,298.621112,263.820410,...,1.053741e+10,2.141192e+08,1.053567e+06,1.179905e+09,5.914764e+08,0.0,0.0,0.0,6.735121,16.678607
min,1.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.000000,0.000000
25%,821.000000,0.000000,0.000000,0.000000,3.169300e+02,1.000000,1.000000,0.000000,1.000000,1.000000,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.000000,0.000000
50%,1641.000000,0.000000,17.340000,509.770000,4.663703e+04,3.000000,4.000000,0.000000,2.000000,2.000000,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.000000,1.000000
75%,2601.000000,0.000000,565.470000,5480.390000,3.040710e+05,11.000000,27.000000,0.000000,5.000000,3.000000,...,9.900000e+01,2.946467e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.000000,2.000000
max,4729.000000,1.000000,430287.670000,482175.490000,1.954861e+06,10000.000000,10000.000000,9995.000000,9999.000000,9287.000000,...,1.000000e+12,1.724181e+10,1.000000e+08,1.120000e+11,5.614756e+10,0.0,0.0,0.0,213.000000,737.000000

In [38]:
df = df.drop(columns=['Index'])

In [39]:
df.select_dtypes(include=['float','int']).describe()

,FLAG,Avg min between sent tnx,Avg min between received tnx,Time Diff between first and last (Mins),Sent tnx,Received Tnx,Number of Created Contracts,Unique Received From Addresses,Unique Sent To Addresses,min value received,...,ERC20 max val rec,ERC20 avg val rec,ERC20 min val sent,ERC20 max val sent,ERC20 avg val sent,ERC20 min val sent contract,ERC20 max val sent contract,ERC20 avg val sent contract,ERC20 uniq sent token name,ERC20 uniq rec token name
count,9841.000000,9841.000000,9841.000000,9.841000e+03,9841.000000,9841.000000,9841.000000,9841.000000,9841.000000,9841.000000,...,9.012000e+03,9.012000e+03,9.012000e+03,9.012000e+03,9.012000e+03,9012.0,9012.0,9012.0,9012.000000,9012.000000
mean,0.221421,5086.878721,8004.851184,2.183333e+05,115.931714,163.700945,3.729702,30.360939,25.840159,43.845153,...,1.252524e+08,4.346203e+06,1.174126e+04,1.303594e+07,6.318389e+06,0.0,0.0,0.0,1.384931,4.826676
std,0.415224,21486.549974,23081.714801,3.229379e+05,757.226361,940.836550,141.445583,298.621112,263.820410,325.929139,...,1.053741e+10,2.141192e+08,1.053567e+06,1.179905e+09,5.914764e+08,0.0,0.0,0.0,6.735121,16.678607
min,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.000000,0.000000
25%,0.000000,0.000000,0.000000,3.169300e+02,1.000000,1.000000,0.000000,1.000000,1.000000,0.001000,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.000000,0.000000
50%,0.000000,17.340000,509.770000,4.663703e+04,3.000000,4.000000,0.000000,2.000000,2.000000,0.095856,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.000000,1.000000
75%,0.000000,565.470000,5480.390000,3.040710e+05,11.000000,27.000000,0.000000,5.000000,3.000000,2.000000,...,9.900000e+01,2.946467e+01,0.000000e+00,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.000000,2.000000
max,1.000000,430287.670000,482175.490000,1.954861e+06,10000.000000,10000.000000,9995.000000,9999.000000,9287.000000,10000.000000,...,1.000000e+12,1.724181e+10,1.000000e+08,1.120000e+11,5.614756e+10,0.0,0.0,0.0,213.000000,737.000000

In [40]:
df['FLAG'].value_counts()

FLAG
0    7662
1    2179
Name: count, dtype: int64